n=int(input("dați număr culorii:"))
if n==1:print("roșu")
if n==2:print("oranj")
if n==3:print("galben")
if n==4:print("verde")
if n==5:print("albastru")
if n==6:print("indigo")
if n==7:print("violet")
print("curcubeul are 7 culori")